In [ ]:
# 주피터노트북 셀 스타일 조절
from IPython.core.display import display, HTML
# display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고메시지 숨기기
# import warnings\

# warnings.filterwarnings(action='ignore')

# Numpy 개요
- Numeric + Python = Numpy
- 수학 및 과학 연산을 위한 파이썬 패키지
- 배열이나 행렬 계산에 용이한 메서드를 제공
- 한글로 넘파이로 주로 통칭, 넘피/늄파이라고
부르기도 함
- 관련 사이트 : http://www.numpy.org

일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원함
- 선형대수와 관련된 다양한 기능을 제공함
- Reference Site
- cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
- https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
- 데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS

### 설치 및 임포트
* 넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
* pip install numpy

In [2]:
import numpy as np
np.__version__

'1.24.3'

In [2]:
# 메소드와 속성
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

# 넘파이 배열 이해하기


## ndim(dimention, rank)
* 몇 차원인지 반환

In [3]:
a = np.array(0)
a, a.ndim, type(a) # ndim : 차원

(array(0), 0, numpy.ndarray)

In [4]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [5]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [6]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

## shape
- 행렬의 차원으로, 몇행 몇열인지 반환
- 아래의 경우 1차원에 4, 2차원에 2로 (4,2)로 표현됨

In [15]:
a.shape?

In [11]:
a = np.array(3)
a, a.shape # 행렬아님

(array(3), ())

In [12]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [13]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [14]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

##  size
요소의 수

In [16]:
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [17]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

## 넘파이 배열
- 리스트를 넘파이 배열로 생성 np.array(리스트)
- 관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [18]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [19]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5


In [20]:
myArr

array([10, 56, 77, 23, 44])

In [21]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [22]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape} 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3) 구조타입 = <class 'tuple'>, size = 9


In [ ]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [ ]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
- 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
- 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
- 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능
(리스트는 문자열 연산만 가능)

In [24]:
# 리스트의 산술연산자 +, *
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할(벡터연산안됨)
# print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


In [26]:
print(listA * 2) # 해당 리스트의 반복
# print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


In [27]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [28]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype
https://numpy.org/doc/stable/reference/arrays.dtypes.html   
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링
dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.   
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다   
숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.



In [29]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [30]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환(문자열이 가장 자리가 크기때문)
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [31]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.   
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.   
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [32]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\User\AppData\Local\Temp\ipykernel_18632\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\User\AppData\Local\Temp\ipykernel_18632\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [33]:
np.log(0)

C:\Users\User\AppData\Local\Temp\ipykernel_18632\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [34]:
np.exp(-np.inf)

0.0

## 기술통계

In [35]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [36]:
np.mean(x)  # 평균

4.8076923076923075

In [37]:
np.var(x)  # 분산

115.23224852071006

In [38]:
np.std(x)  # 표준 편차

10.734628476137871

In [39]:
np.max(x)  # 최댓값

23

In [40]:
np.min(x)  # 최소값

-24

In [41]:
np.median(x)  # 중앙값

5.0

### 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.   
각각 1사분위수, 2사분위수, 3사분위수라고 한다.   
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.   

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.


In [42]:
np.percentile(x, 0)  # 최소값

-24.0

In [43]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [44]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [45]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [47]:
np.percentile(x, 100)  # 최댓값

23.0

## 넘파이 함수로 배열 만들기

np.ones(n)  , np.ones((x, y))   
np.zeros(n) , np.zeros((x, y))   
np.empty(n) , np.empty((x, y))   
np.aranges(start, end step)   

reshape(x, y) # 차원 확대   
flatten(x, y) # 차원 축소

In [48]:
# 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [49]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [50]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [51]:
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [ ]:
# 메모리가 비어있음 -> 메모리 초기화안됨
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int)) # 기존 메모리에 있던 값을 출력(알수없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[         0          0 1963503984]
 [       419 1963505504        419]
 [1963506544        419    6750318]]


```
zeros -> 메모리 할당받아0으로 초기화한 뒤 반환
empty -> 메모리 할당만 받고 초기화 없이 반환
```

In [53]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [54]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [55]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [56]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 개수

array([  0.,  25.,  50.,  75., 100.])

In [57]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,   
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [58]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [59]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [60]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [61]:
# 2차원 -> 1차원
# 넘파이배열.flatten() -> 순서를 나타내고 싶을 때
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [ ]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
print(np.arange(2,101,2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [ ]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [62]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [63]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(-1, 4)
# rehsape -1은, 행무관하고 n개의 컬럼을 만든다

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [64]:
np.arange(1, 21).reshape( 4, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# 사이즈가 맞아야 한다.
# np.arange(1, 21).reshape(-1, 7)

ValueError: cannot reshape array of size 20 into shape (7)

In [65]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [66]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [67]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [68]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [69]:
a.shape = -1, 2
a, a.shape

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 (6, 2))

In [70]:
a.shape = -1, 3
a, a.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [71]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

## 넘파이배열의 자료형 형변환

배열명2 = 배열명1.astype(자료형)   
자료형 = np.float64, np.int32

In [72]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [73]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [74]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [ ]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [75]:
# 정수형 => 문자열(유니코드)
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [76]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [77]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [78]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [79]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [ ]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [80]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

## 넘파이 배열의 인덱싱

넘파이배열[index]
넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

### 1D array

In [81]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [82]:
a[0]

1

In [83]:
a[2]

5

In [84]:
a[4]

9

In [85]:
a[-1]

9

In [86]:
a[-3]

5

In [87]:
a[-5]

1

In [88]:
a[[0, 2, 4]]

array([1, 5, 9])

In [89]:
a

array([1, 3, 5, 7, 9])

In [90]:
# 행렬 구조로 인덱싱도 가능하다
i = np.array([[1,3], [4,2]])
i

array([[1, 3],
       [4, 2]])

In [91]:
# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[i]

array([[3, 7],
       [9, 5]])

In [92]:
a[2] = 0
a

array([1, 3, 0, 7, 9])

In [93]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [94]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

### 2D array

In [95]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [96]:
a[0] # 2차원 인덱싱할 때 값하나만 넣으면 행

array([0, 1, 2, 3, 4])

In [97]:
a[1]

array([5, 6, 7, 8, 9])

In [98]:
a[2]

array([10, 11, 12, 13, 14])

In [99]:
a[-1]

array([10, 11, 12, 13, 14])

In [100]:
a[-2]

array([5, 6, 7, 8, 9])

In [101]:
a[-3]

array([0, 1, 2, 3, 4])

In [102]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
a[0, 0]

0

In [104]:
a[0, 1]

1

In [105]:
a[0, 2]

2

In [106]:
a[1, 0]

5

In [107]:
a[1, 1]

6

In [108]:
a[1, 2]

7

In [109]:
a[2, 0]

10

In [110]:
a[2, 1]

11

In [111]:
a[2, 2]

12

In [112]:
a[-1, 0]

10

In [113]:
a[-1, 1]

11

In [114]:
a[-1, 2]

12

In [115]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [116]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [117]:
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [118]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [124]:
a[1,1] = 3
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [119]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [125]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [126]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0] # 성능이 중요할 때

0

In [127]:
matrix_b[0][0] # 가독성이 중요할 때

0

In [128]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
# 2차원 마지막행 마지막열 -> 3행 4열
matrix_b[-1,-1]

11

In [130]:
matrix_b[-1][-1]

11

In [131]:
matrix_b[2][3]

11

In [132]:
# matrix_b에서 3번째행 1번째열의값을 100으로 변경해보자
matrix_b[2,0] = 100
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

## 넘파이배열 슬라이싱


* 1차원
- 넘파이배열[:end]
- 넘파이배열[start:]
- 넘파이배열[start:end]
- 넘파이배열[start:end:step]

* 2차원
- 넘파이배열[행, 열] = [start:end:step, start2:end2:step2]

### 1D array

In [133]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [134]:
a[:]

array([1, 3, 5, 7, 9])

In [135]:
 a[1:]

array([3, 5, 7, 9])

In [136]:
a[-1:]

array([9])

In [137]:
a[:3]

array([1, 3, 5])

In [138]:
a[:-1]

array([1, 3, 5, 7])

In [139]:
a[1:4]

array([3, 5, 7])

In [140]:
a[1:-1]

array([3, 5, 7])

In [141]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
a[::2]

array([0, 2, 4, 6, 8])

In [143]:
a[::5]

array([0, 5])

In [144]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [145]:
# 홀수
a[1::2]

array([1, 3, 5, 7, 9])

In [146]:
a[3::2]

array([3, 5, 7, 9])

In [147]:
a[:-2:2]

array([0, 2, 4, 6])

In [148]:
a[:-6:2]

array([0, 2])

In [149]:
a[2:-2:2]

array([2, 4, 6])

### 2D array

In [150]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [151]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [152]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [153]:
a[3:]

array([], shape=(0, 5), dtype=int32)

In [154]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [155]:
a[-3:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [156]:
a[:0] # 다차원 슬라이싱은 행자체로 슬라이싱

array([], shape=(0, 5), dtype=int32)

In [157]:
a[:2] 

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [158]:
a[:-1]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [159]:
a[:-3]

array([], shape=(0, 5), dtype=int32)

In [160]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [161]:
a[:, :]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [162]:
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [163]:
a[:, 3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [164]:
a[:, -1:]

array([[14],
       [19],
       [24]])

In [165]:
a[:, -4:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [166]:
a[:, :1]

array([[10],
       [15],
       [20]])

In [167]:
a[:, :5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [168]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [169]:
a[:, :-1]

array([[10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [170]:
a[:, :-2]

array([[10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [171]:
a[:, 0:1]

array([[10],
       [15],
       [20]])

In [172]:
a[:, 2:3]

array([[12],
       [17],
       [22]])

In [174]:
a[:, 1:-1]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [175]:
a = np.arange(10, 100).reshape(9, 10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
a[2:5, :]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [177]:
a[:, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [178]:
a[2:5, 2:5]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [179]:
a[::2, ::2]

array([[10, 12, 14, 16, 18],
       [30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [180]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
a[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [183]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 numpy.ndarray,
 2)

In [184]:
# 1차원 슬라이싱, 1행만 출력
matrix_c[0, :], matrix_c[0]

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [185]:
# 2차원 슬라이싱, 1번째행 2번째행 출력
matrix_c[0:2, :], matrix_c[0:2]

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]))

In [186]:
# 1번째열만 출력
matrix_c[:, 0]

array([ 1,  6, 11, 16, 21])

In [187]:
# 3,4 번째열만 출력
matrix_c[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [188]:
# 특정행의 특정열 슬라이싱
matrix_c[0:3, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [189]:
# 홀수번째 행만 출력
matrix_c[::2, ::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [190]:
# 짝수번쨰행 + 홀수번째열
matrix_c[1::2, ::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

In [191]:
# 리버스 인덱싱
print(matrix_c[::-1, ::]) # 행 뒤집기
print(matrix_c[::, ::-1]) # 열 뒤집기

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


### 전치행렬
넘파이배열.T : 행과 열 구조 변경

In [192]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [193]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [194]:
# reshape과 transpose은 값이 다름을 유의
print(matrix_d.reshape(2,3))

[[1 2 3]
 [4 5 6]]


### 난수로 구성된 넘파이 배열

np.random.randint(start, end, n) : 정수 난수   
np.random.randint(start, end, (i, j))


In [77]:
random.randint? # generation모듈 : 값을 만들어줌

SyntaxError: invalid syntax (352209998.py, line 1)

In [196]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([6, 6, 2, 7, 7, 3, 4, 9, 2, 7])

In [197]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[8, 6, 2, 3, 8],
       [9, 8, 8, 1, 8]])

### 섞기
np.random.shuffle(넘파이배열)
원본에 바로 적용

In [198]:
np.random.shuffle?

In [199]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [200]:
np.random.shuffle(matrix_e)
matrix_e

array([ 5,  2,  3,  4,  8,  6,  1,  9, 10,  7])

#### Quiz : 1~46까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [201]:
num= np.arange(1,47)
np.random.shuffle(num)
num[:6]

array([42, 30, 21, 11,  9,  6])

In [202]:
np.random.randint(1,47,6) # 중복 허용 

array([ 3, 28, 13, 39, 45, 33])

### 실수 난수
 np.random.randn(n)
 np.random.randn(i, j)

In [203]:
np.random.randn?

In [204]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([ 0.62816514,  1.34891572,  1.41721454,  0.29485519, -0.23592872,
        1.6773335 , -1.02414484, -1.79923605,  0.73285364, -0.10742826])

In [205]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-0.59709975, -0.45615811,  2.23963436, -0.02591641],
       [ 0.93024525, -0.92160454, -0.47070584,  0.0997941 ],
       [ 0.43927115,  0.8136203 ,  0.79293305, -0.92297549],
       [-0.50666941, -0.66352714, -0.69800957, -0.19491772]])

In [206]:
matrix1.max(), matrix1.min()

(1.6773335035036256, -1.7992360487399583)

### 집계함수에서의 축

- 2차원에서의 집계합수(sum, mean)
- axis = 0, 1
- np.sum(넘파이배열, axis=0/1)
- np.mean(넘파이배열, axis=0/1)
- np.sort(넘파이배열, axis=0/1)

In [207]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[13, 30, 48, 34, 29],
       [11, 48,  5, 39, 16],
       [32,  6,  2, 38, 11],
       [ 2,  4, 28, 45, 33],
       [30, 34, 44,  6, 46]])

In [208]:
np.sum(m1, axis=0) # 각 (x)행 방향 합계

array([ 88, 122, 127, 162, 135])

In [210]:
np.sum(m1, axis=1) # 각 열(y) 방향 합계

array([154, 119,  89, 112, 160])

In [212]:
m1[0,:]

array([13, 30, 48, 34, 29])

In [213]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

154

### np.sort()

In [18]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[29, 37, 31],
       [35, 49, 20],
       [29, 27, 25],
       [ 4,  4, 26]])

In [17]:
np.sort?

In [19]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[ 4,  4, 20],
       [29, 27, 25],
       [29, 37, 26],
       [35, 49, 31]])

In [20]:
np.sort(m2)

array([[29, 31, 37],
       [20, 35, 49],
       [25, 27, 29],
       [ 4,  4, 26]])

In [22]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[ 4,  4, 26],
       [29, 27, 25],
       [35, 49, 20],
       [29, 37, 31]])

In [23]:
np.sort(m2, axis=1) # 열방향 오름차순

array([[29, 31, 37],
       [20, 35, 49],
       [25, 27, 29],
       [ 4,  4, 26]])

### 인덱스 소팅

np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로) 원본값 변경 x

In [24]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값

array([2, 1, 0], dtype=int64)

In [25]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

### 넘파이 배열 요소 추가와 삭제
- 삽입
    - np.insert(배열, 위치인덱스, 값, axis=0/1)
    - 2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력

- 삭제
    - np.delete(배열명, 위치인덱스, axis=0/1)

In [26]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [28]:
m3[-1]

10

In [29]:
np.insert?

In [30]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [31]:
np.insert(m3, len(m3), 500)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [38]:
m4 = np.arange(1,16).reshape(3,5)
m4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
m4.shape

(3, 5)

In [40]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [41]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3,   4,   5],
       [100,   6,   7,   8,   9,  10],
       [100,  11,  12,  13,  14,  15]])

In [44]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3,   4,   5],
       [200,   6,   7,   8,   9,  10],
       [300,  11,  12,  13,  14,  15]])

In [43]:
np.insert(m4, 0, 100, axis=0)

array([[100, 100, 100, 100, 100],
       [  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15]])

In [42]:
m4.shape, m4.shape[1], len(m4)

((3, 5), 5, 3)

In [46]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3,   4,   5, 100],
       [  6,   7,   8,   9,  10, 200],
       [ 11,  12,  13,  14,  15, 300]])

In [49]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100], axis=0)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100]])

In [50]:
m4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [51]:
np.delete(m4, 0, axis=0)

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### 배열 합치기
- np.vstack((배열1,배열2....)) : 세로 합치기
- np.hstack((배열1,배열2....)) : 가로 합치기
- np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [54]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [55]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [56]:
f = np.concatenate((c,d), axis=0) # 행방향 합치기
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [57]:
f = np.concatenate((c,d), axis=1) # 열방향 합치기
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

### boolean indexing, mask
- 조건절의 결과는 True, False로 반환
- True인 결과의 데이터 반환
- 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [58]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [59]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [60]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [61]:
(matrix > 10).sum()

10

#### Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [62]:
num = np.random.randint(1,100,30)
(num > 30) & (num < 70)

array([ True, False,  True,  True,  True, False, False, False, False,
        True,  True, False, False, False, False,  True,  True, False,
       False, False,  True,  True, False, False, False, False,  True,
        True, False,  True])

In [63]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([45, 87, 28, 84, 91, 61, 69, 74, 76, 67,  8, 44, 71, 10, 66, 69, 33,
        36, 80, 74,  1, 24, 64, 15, 62, 66, 94, 44, 34, 54]),
 array([45, 61, 69, 67, 44, 66, 69, 33, 36, 64, 62, 66, 44, 34, 54]))

In [64]:
# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([28,  8, 10,  1, 24, 15])

In [65]:
# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([91,  8,  1, 94])

In [66]:
 num[~(num < 10) | (num > 90)]

array([45, 87, 28, 84, 91, 61, 69, 74, 76, 67, 44, 71, 10, 66, 69, 33, 36,
       80, 74, 24, 64, 15, 62, 66, 94, 44, 34, 54])

### fancy indexing(filtering)
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.
- 넘파이배열1[넘파이배열2]
- 넘파이배열2 : 인덱스 역할 (only 정수형)

In [67]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([52, 20, 50, 92,  2, 77, 52, 11, 53, 48, 58, 98, 84, 34, 14, 67, 12,
        47, 61, 19, 22, 55, 96, 92,  3, 99,  8,  4, 26, 49]),
 array([52, 50, 92, 58, 22]))

### np.where()를 이용한 필터링
- np.where(조건식) : 조건식 만족하는 인덱스 반환
- np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
- 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값


In [68]:
np.where?

In [69]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [70]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))

In [71]:
b[np.where(b<25)]

array([20, 21, 22, 23, 24])